config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :cows
  resources :comments
  resources :characters, :controller => "cows"

  root 'cows#index'

  get 'ping/:id' => 'cows#ping', :as => :ping, :constraints => { :id => /.+/ }

end

app/models/comment.rb
class Comment < ActiveRecord::Base
end

app/models/cow.rb
class Cow < ActiveRecord::Base

  def host
    URI.parse(url).host
  end

  def self.ping(host)
    case RUBY_PLATFORM
    when /darwin/
      opt = "-t"
    else
      opt = "-c"
    end
    `ping #{opt} 1 #{host}`
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable #, :registerable,
         # :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
    # For APIs, you may want to use :null_session instead.
    protect_from_forgery with: :exception

    def resource_name
        :user
    end

    def resource
        @resource ||= User.new
    end

    def devise_mapping
        @devise_mapping ||= Devise.mappings[:user]
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:content, :score, :post_id)
    end
end

app/controllers/cows_controller.rb
class CowsController < ApplicationController
  before_action :set_cow, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:edit, :update, :destroy]

  # GET /cows
  # GET /cows.json
  def index
    @cows = Cow.all
  end

  # GET /cows/1
  # GET /cows/1.json
  def show
      if @cow.url and @cow.url.index("https") == 0 then
          @secure = '<i class="fa fa-check"></i> (' + @cow.url[0..3] + ')'
      else
          @secure = '<i class="fa fa-exclamation"></i>'
      end
  end

  # GET /cows/new
  def new
    @cow = Cow.new
  end

  # GET /cows/1/edit
  def edit
  end

  # GET /cows/1/ping:
  def ping
  end

  # POST /cows
  # POST /cows.json
  def create
    @cow = Cow.new(cow_params)

    respond_to do |format|
      if @cow.save
        format.html { redirect_to @cow, notice: 'Cow was successfully created.' }
        format.json { render :show, status: :created, location: @cow }
      else
        format.html { render :new }
        format.json { render json: @cow.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cows/1
  # PATCH/PUT /cows/1.json
  def update
    respond_to do |format|
      if @cow.update(cow_params)
        format.html { redirect_to @cow, notice: 'Cow was successfully updated.' }
        format.json { render :show, status: :ok, location: @cow }
      else
        format.html { render :edit }
        format.json { render json: @cow.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cows/1
  # DELETE /cows/1.json
  def destroy
    @cow.destroy
    respond_to do |format|
      format.html { redirect_to cows_url, notice: 'Cow was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cow
      # @cow = Cow.find(params[:id])
      # Injectable find_by_sql: 
      @cow = Cow.find_by_sql("SELECT * FROM cows WHERE id=#{params[:id]}").first
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cow_params
      params.require(:cow).permit(:name, :location, :birthday, :height, :weight, :single, :score, :url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/cows_helper.rb
module CowsHelper
end

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :score %><br>
    <%= f.number_field :score %>
  </div>
  <div class="field">
    <%= f.label :post_id %><br>
    <%= f.number_field :post_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>Score</th>
      <th>Post</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.content %></td>
        <td><%= comment.score %></td>
        <td><%= comment.post_id %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @comment.content %>
</p>

<p>
  <strong>Score:</strong>
  <%= @comment.score %>
</p>

<p>
  <strong>Post:</strong>
  <%= @comment.post_id %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/cows/_form.html.erb
<%= form_for(@cow) do |f| %>
  <% if @cow.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cow.errors.count, "error") %> prohibited this character from being saved:</h2>

      <ul>
      <% @cow.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :url%><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :birthday %><br>
    <%= f.date_select :birthday, start_year: 1985 %>
  </div>
  <div class="field">
    <%= f.label :height %><br>
    <%= f.number_field :height %>
  </div>
  <div class="field">
    <%= f.label :weight %><br>
    <%= f.number_field :weight %>
  </div>
  <div class="field">
    <%= f.label :single %><br>
    <%= f.check_box :single %>
  </div>
  <div class="field">
    <%= f.label :score %><br>
    <%= f.number_field :score %>
  </div>
  <div class="actions">
    <%= f.submit :value => "Create a character" %>
  </div>
<% end %>

app/views/cows/_score.html.erb
  <% score = cow.score.to_i %>
  <% score = 0 unless 0 <= score and score <= 5 %>
  <% score.times do %>
    <span style="color: #f1c40f;" class="glyphicon glyphicon-star" aria-hidden="true"></span>
  <% end %>
  <% (5 - score).times do %>
    <span class="glyphicon glyphicon-star-empty" aria-hidden="true"></span>
  <% end %>

app/views/cows/edit.html.erb
<h1>Editing Star Wars characters</h1>

<%= render 'form' %>

<%= link_to 'Show', character_path(@cow) %> |
<%= link_to 'Back', characters_path %>

app/views/cows/index.html.erb
<header class="row">
  <img src="header.jpg" alt="">
</header>

<div class="row">
  <div class="col-lg-12">
    <p id="notice"><%= notice %></p>

    <div class="col-md-3">
      <form class="navbar-form" role="search" action="/" method="get">
        <div class="form-group">
          <input name="search" type="text" class="form-control" placeholder="Type here" value="<%= raw params[:search] %>">
        </div>
        <button type="submit" class="btn btn-default">Search</button>
      </form>

      <div class="well">
        <h4>
          <%= link_to raw('<i class="fa fa-plus-circle fa3"></i> Add your character'), new_character_path %>
        </h4>
      </div>
      <div class="well">
        <h4>Star Wars Characters of the month</h4>
        <p>The character of the month has not been elected yet. Please come back later!</p>
      </div>
      <div class="well">
        <h4>
          <i class="fa fa-twitter"></i>
          Last tweets
        </h4>
        <p>None yet!</p>
      </div>
    </div>

    <div class="col-md-9">
      <pre>
      Uname: <%=`uname -a`.chomp%>
      Cmdline: <%= $0 %> <%= ARGV.join(' ') %>
  <% if defined?(Sqreen) %>
      Sqreen: <%= Sqreen::VERSION %>
      Sqreen token: <%= Sqreen.config_get :token %>
      Sqreen URL: <%= Sqreen.config_get :url %>
      Sqreen logged in: <%= Sqreen.logged_in %>
      Sqreen js: <%= Sqreen::Rules::ExecJSCB.js_service.variant  if Sqreen::Rules::ExecJSCB..respond_to?(:js_service) %>
  <% else %>
      Sqreen not defined</li>
  <% end %>
      Sqreen mini racer version: <%=  Sqreen::MiniRacer::VERSION if defined?(Sqreen::MiniRacer) %>
      Exec js runtime: <%= ExecJS.runtime.inspect %>
      Exec js result: <%= ExecJS.eval "'red yellow blue'.split(' ')" %>
    </pre>
    <h3>Sqreen.log</h3>
    <pre>
    <%= path = File.join(Rails.root, "log", "sqreen.log")
      if File.exists?(path) then
        File.read(path)
      else
        "no file '#{path}' found"
      end
      %>
    </pre>
    </div>
    <div class="col-md-9 char-list">
      <h2 class="col-lg-12">Vote for your favorite character!</h2>
      <% @cows.each do |cow| %>
      <div class="col-xs-12 col-sm-6 col-md-4">
        <div class="card">
          <div class="card-image">
            <img src="<%= cow.url %>" class="img-responsive" alt="...">
          </div>
          <div class="card-content">
            <h3><%= cow.name %></h3>
            <p><%= render partial: 'score', :locals => {cow: cow} %></p>
            <p class="desc"><%= cow.description %></p>
            <p class="date"><%= cow.birthday %></p>

            <div class="btn-ctn">
              <%= link_to 'Details', character_path(cow), :class => "detail" %>
              <%= link_to raw('<i class="fa fa-thumbs-o-up"></i> Vote'), "#", :class => "vote" %>
            </div>
          </div>
        </div>
      </div>
      <% end %>
    </div>
  </div>

app/views/cows/new.html.erb
<h1>New Star Wars character</h1>

<%= render 'form' %>

<%= link_to 'Back', characters_path %>

app/views/cows/ping.html.erb
Let's check <%= params[:id] %> aliveness:
<pre>
<%= Cow.ping(params[:id]) %>
</pre>

app/views/cows/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-lg-12 back">
    <%= link_to raw('<i class="fa fa-arrow-left"></i> ') + 'Back', characters_path, :class => "btn btn-default" %>
  </div>
</div>

<div class="row">
  <div class="col-md-6 thumb">
    <div class="thumbnail center-block">
      <div style="">
        <%
         if @cow and not @cow.url.to_s =~ /[<>]/ then
           url = (@cow.url_big || @cow.url).html_safe
         else
           url = @cow.url_big || @cow.url
         end
        %>
        <img src="<%= url %>" class="img-responsive" alt="<%= @cow.name %>">
      </div>
    </div>
  </div>
  <div class="col-md-6 content">
    <div class="caption">
      <h2><%= raw @cow.name %></h2>
      <p><%= @cow.description %></p>
      <div>
        <strong>Url :</strong>
        <p><%= @cow.url_big %></p>
      </div>
      <div>
        <strong>Location :</strong>
        <p><%= @cow.location %></p>
      </div>
      <div>
        <strong>Birthday :</strong>
        <p><%= @cow.birthday %></p>
      </div>
      <div>
        <strong>Score :</strong>
        <p><%= render partial: 'score', :locals => {cow: @cow} %></p>
      </div>
    </div>
    <%= link_to raw('<i class="fa fa-thumbs-o-up"></i> ') + 'Vote', "#", :class => "btn btn-info" %>
    <%= link_to raw('<i class="fa fa-pencil"></i> ') + 'Edit', edit_character_path(@cow), :class => "btn btn-warning" %>
    <%= link_to raw('<i class="fa fa-link"></i> ') + 'Alive?', ping_path(1), :class => "" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Star Wars characters</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <style>
      body {
        padding-top: 70px;
        /* Required padding for .navbar-fixed-top. Remove if using .navbar-static-top. Change if height of navigation changes. */
      }
      footer {
        margin: 50px 0;
      }
    </style>
  </head>
  <body>
    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">
            <img src="/sw-logo.png" alt="">
            <!-- <span>My Favorite</span> -->
          </a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li>
              <a href="#">About</a>
            </li>
            <li>
              <a href="#">Services</a>
            </li>
            <li>
              <a href="#">Contact</a>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
            <li>
              <%= link_to(raw('<i class="fa fa-sign-out"></i> Logout'), destroy_user_session_path, :method => :delete) %>
            </li>
            <% else %>
            <li></i><%= link_to(raw('<i class="fa fa-sign-in"></i> Login'), new_user_session_path)  %></li>
            <% end %>
          </ul>
      </div>
      <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
    </nav>

    <div class="container bs-docs-container">
      <div class="row">
        <div class="col-lg-12 alert-ctn">
          <% if notice %>
          <div class="notice alert alert-info alert-dismissable">
            <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
            <%= notice %>
          </div>
          <% end %>
          <% if alert %>
          <div class="alert alert-danger alert-dismissable">
            <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
            <%= alert %>
          </div>
          <% end %>
        </div>
      </div>
      <%= yield %>
    </div>
  </body>
</html>